BB_CONF_FRAGMENT_SUMMARY = "KF6 CI defaults for autobuilds"
BB_CONF_FRAGMENT_DESCRIPTION = "KF6 CI defaults for autobuilds"

LICENSE_FLAGS_ACCEPTED += "commercial"

DISTRO_FEATURES = "polkit systemd usrmerge wayland vulkan"
DISTRO_FEATURES:remove = "sysvinit"

VIRTUAL-RUNTIME_init_manager = "systemd"

INHERIT += "rm_work"

# limit computation: ncpus/4
BB_NUMBER_THREADS = "4"
OMP_NUM_THREADS = "4"
