BB_CONF_FRAGMENT_SUMMARY = "KF6 CI sstate seeding for Wrynose"
BB_CONF_FRAGMENT_DESCRIPTION = "KF6 CI sstate seeding for Wrynose"

SSTATE_MIRRORS += "file://.* https://storage.kde.org/yocto-sstate/wrynose/PATH;downloadfilename=PATH"

# host local cache: for sstate sharing without hash equiv server only basic hash works
BB_HASHSERVE = ""
BB_SIGNATURE_HANDLER = "OEBasicHash"
SSTATE_DIR = "/mnt/yocto_sstate_wrynose"
